# Generated by Django 4.1 on 2022-11-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="fandom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to="fics.fandom",
            ),
        ),
    ]
