# Generated by Django 4.1 on 2022-11-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fics", "0002_character_fandom"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="characters",
            field=models.ManyToManyField(related_name="ships", to="fics.character"),
        ),
    ]
